### ISSUE TITLE
Specify watch events

### ISSUE THREAD

**Issue by bndw** [go-fsnotify/fsnotify#103]
I'd like to be able to specify the events being watched for. For example, I'm working on an application that is **only** concerned with `IN_CREATE`. The current implementation appears to use a [hard coded set of events](https://github.com/go-fsnotify/fsnotify/blob/v1.2.5/inotify.go#L98-L100).

If this feature is inline with the project's roadmap, I'd be glad to take a stab at it.

**Comment by nathany** [comment]
The current solution is to filter out the events you get back. Indicating which events to watch is an optimization, though not all platforms will be able to filter the same way. Please take a look at #7.

I'm closing this is a duplicate. If you want to take a stab at it, I'd be happy to review a pull request. Feel free to discuss further at #7.
