### ISSUE TITLE
inotify is leaking a file descriptor

### ISSUE THREAD

**Issue by nathany** [go-fsnotify/fsnotify#3]
Reported by @alberts at https://codereview.appspot.com/8202043/#msg6

> I noticed that TestFsnotifyDeleteWatchedDir is leaking a file descriptor:

 > ```console
strace -f -q -e inotify_init,open,close ./fsnotify.test
-test.cpu=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
-test.v -test.run=TestFsnotifyDeleteWatchedDir
```

> SIGABRT shows that all the readEvents goroutines (which are in charge of closing
the inotify fd) are still stuck in their read syscall.
> This seems like a problem with the current design of Watcher. readEvents is
blocked and can't see the closed done channel.

See #5 regarding blocking behaviour.

**Comment by nathany** [comment]
I don't know what I'm doing :-1: 

```
strace: Can't stat './fsnotify.test': No such file or directory

GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
./fsnotify.test: No such file or directory.
```

**Comment by PieterD** [comment]
go test -c
