### ISSUE TITLE
fsnotify.Write is not catching updates on Mac

### ISSUE THREAD

**Issue by jimzhan** [go-fsnotify/fsnotify#54]
```go
if event.Op&fsnotify.Write == fsnotify.Write {
    log.Println("modified file:", event.Name)
}
```

Events trigged: RENAME -> CREATE -> CHMOD -> CHMOD -> CHMOD

The exact example is not catching the event after file updates.

**Comment by nathany** [comment]
Yah, it would be nice. But unfortunately that's more to do with how the underlying event monitoring systems work and how editors save files than with fsnotify.
