### ISSUE TITLE
OpCode 6

### ISSUE THREAD

**Issue by arianitu** [go-fsnotify/fsnotify#58]
When the watching directory is deleted, sometimes I get OpCode 6, and not 4. I don't see it as a constant, what is that op code?

**Comment by nathany** [comment]
Hi. Which operating system are you seeing this on?

**Comment by nathany** [comment]
Ops are a bit mask so it is a combination of events (4 as well as 2)

See the example_test.go to check for individual flags.

**Comment by arianitu** [comment]
Ah! That makes sense.
