### ISSUE TITLE
File handle leak on OS X

### ISSUE THREAD

**Issue by neelance** [go-fsnotify/fsnotify#59]
The following code quickly runs into a `panic: too many open files` on OS X, even though the documentation says that `Close` removes all watches.
```
package main

import "gopkg.in/fsnotify.v1"

func main() {
	for {
		println("loop")

		w, err := fsnotify.NewWatcher()
		if err != nil {
			panic(err)
		}

		go func() {
			for range w.Events {
			}
		}()
		go func() {
			for range w.Errors {
			}
		}()

		if err := w.Add("test.go"); err != nil {
			panic(err)
		}

		// uncomment this to make the leak go away
		// if err := w.Remove("test.go"); err != nil {
		// 	panic(err)
		// }

		if err := w.Close(); err != nil {
			panic(err)
		}
	}
}
```

**Comment by nathany** [comment]
Thanks for reporting this.

**Comment by nathany** [comment]
@PieterD I'm looking this on OS X and BSD, but it also fails on Linux:

using `import "github.com/go-fsnotify/fsnotify"`

```
panic: inotify_init: too many open files
```

**Comment by PieterD** [comment]
This would cause a tremendous amount of problems. With my next pull, I've got w.Close waiting until the goroutine is done. That will fix this.

**Comment by nathany** [comment]
Excellent.

**kqueue**

This is interesting, as Close just calls Remove for all watches. Another race condition? 
Close is ignoring the errors that Remove sends back, in this case: "bad file descriptor"

**Comment by PieterD** [comment]
If Close just removes all watches but the goroutine blocks on something, the goroutines will start heaping up as you keep adding more goroutines, all blocking, all keeping open files.

They don't even have to block; if you create the next goroutine without waiting for the last one to finish, you could create a thousand before the first goroutine has a chance to clean up.

**Comment by PieterD** [comment]
Confirmed that https://github.com/go-fsnotify/fsnotify/pull/66 fixes this for inotify. For OS X, I suggest making sure Close waits until the goroutine is stopped before returning.

**Comment by nathany** [comment]
Thanks @PieterD. I've already merged a fix for OS X, but I have yet to tag a new release. Tomorrow once the poll stuff is in.
