### ISSUE TITLE
Received EINTR on error chan

### ISSUE THREAD

**Issue by PieterD** [go-fsnotify/fsnotify#61]
I just got this:
Error from fsnotify: read: interrupted system call

At first glance, this does not look like something that was meant to happen, but I may be mistaken. I don't know what caused it, and I have not yet had time to reproduce it, but I could give it a shot if you wish.

**Comment by PieterD** [comment]
Dang, I was going to check my version, but I'm using golang.org/x/exp/fsnotify, which is not this repository. Sorry for the noise.

**Comment by nathany** [comment]
If you run into the same issue with this repo, please let me know what OS you are using and some example code of possible.

I should really send a CL to remove x/exp/fsnotify.

**Comment by PieterD** [comment]
I will try to do both tonight. If I manage to reproduce it with golang.org/x/exp/fsnotify (it looks very timing-sensitive) I'll try to do the same with this one.

More info to follow, but it may have to wait for a bit because work. I'm on Linux/x64.

**Comment by nathany** [comment]
Thanks Pieter.

x/exp is quite a ways behind this repo, but very little has changed on Linux.

**Comment by PieterD** [comment]
The problem appears in both fsnotify packages. I'm afraid it might be in syscall, specifically InotifyInit. I hope not, because that would be bad news.

I could reproduce the problem with this:
```
package main

import (
  "time"
  "fmt"
  "github.com/go-fsnotify/fsnotify"
  "os"
  "syscall"
)

func Panic(err error) {
  if err != nil {
    panic(err)
  }
}

func main() {
  go sig()
  go notify()
  <-time.After(5 * time.Second)
}

func notify() *fsnotify.Watcher {
  w, err := fsnotify.NewWatcher()
  Panic(err)
  defer w.Close()
  err = w.Add(".")
  Panic(err)
  defer w.Remove(".")
  for {
    select {
    case err := <-w.Errors:
      Panic(fmt.Errorf("fsnotify error from Error channel: %#v", err))
    case <-w.Events:
    }
  }
}

func sig() {
  p, err := os.FindProcess(os.Getpid())
  Panic(err)
  for {
    p.Signal(syscall.SIGUSR1)
  }
}

```

**Comment by PieterD** [comment]
See also https://github.com/golang/go/issues/9782

**Comment by PieterD** [comment]
Of course it could be as simple as ignoring EINTR, which might be where this is going.

**Comment by nathany** [comment]
Thanks for the example. I'll try to take a look on the weekend.

If you want to try adding some logging into inotify.go and poke around, any help would be appreciated.

**Comment by PieterD** [comment]
I'll take a look at this tonight and keep you posted.

**Comment by PieterD** [comment]
Okay, so it uses syscall.Read, and it blocks. So it will need at least a runtime.LockOSThread in the readEvents goroutine, I think.

Second, it can get interrupted by signals, so it needs a little help ignoring EINTR.

**Comment by PieterD** [comment]
Ian cleared it up for me, no need for runtime.LockOSThread. I'll fix up the EINTR thing in the near future.

**Comment by PieterD** [comment]
Pull requested: https://github.com/go-fsnotify/fsnotify/pull/62

I think you'll like the Go issue that this spawned: https://github.com/golang/go/issues/9785

That issue also explains why EINTR was happening.

**Comment by nathany** [comment]
Thanks very much!

I'll take care of exp/fsnotify.

**Comment by nathany** [comment]
merged.

**Comment by nathany** [comment]
I sent in a CL to remove exp/fsnotify. https://go-review.googlesource.com/#/c/3990/1

**Comment by PieterD** [comment]
Nice. I sent you an email regarding some other work on inotify.

**Comment by PieterD** [comment]
Never mind, I got carried away and already made a pull request.
