### ISSUE TITLE
watcher.Errors channel spamming <nil> events (kqueue, OSX)

### ISSUE THREAD

**Issue by pbdeuchler** [go-fsnotify/fsnotify#68]
Howdy,

I'm implementing a very simple file watcher, almost identical to the example given in the repo. However immediately upon running I get spammed with incessant `<nil>` errors from the watcher.Errors channel. 

Beyond the root cause it's puzzling to me that this could happen, since I checked the source and you guys do the standard `if err != nil` check for any place you send an error over the wire

Code:
```go
func (dr *DiskRecieve) Run() error {
	watcher, err := fsnotify.NewWatcher()
	if err != nil {
		log.Fatal(err)
	}
	defer watcher.Close()
	fmt.Printf("monitor dir: %s \n", dr.monitorDir)
	go func() {
		for {
			select {
			case event := <-watcher.Events:
				if event.Op&fsnotify.Write == fsnotify.Write { // We only want write events, correct?
					log.Println("new write file event:", event.Name)
					dr.wd.Acquire()
					go dr.processEvent(event)
				}
			case err := <-watcher.Errors:
				log.Println("file watcher error:", err)
			}
		}
	}()

	err = watcher.Add(dr.monitorDir)
	if err != nil {
		log.Fatal(err)
	}
	return err
}
```

Output:
```bash
2015/02/11 18:37:50 file watcher error: <nil>
2015/02/11 18:37:50 file watcher error: <nil>
2015/02/11 18:37:50 file watcher error: <nil>
2015/02/11 18:37:50 file watcher error: <nil>
2015/02/11 18:37:50 file watcher error: <nil>
2015/02/11 18:37:50 file watcher error: <nil>
2015/02/11 18:37:50 file watcher error: <nil>
2015/02/11 18:37:50 file watcher error: <nil>
2015/02/11 18:37:50 file watcher error: <nil>
2015/02/11 18:37:50 file watcher error: <nil>
...
```

**Comment by nathany** [comment]
Wow, that is odd. Your code looks good to me, so I'm going to have to do some digging.

What is your import path and is fsnotify the very latest version?

**Comment by pbdeuchler** [comment]
```go
import (
	"bufio"
	"fmt"
	"gopkg.in/fsnotify.v1"
	"log"
	"os"
)
```

go-get'd just a couple hours before I made the issue

**Comment by PieterD** [comment]
That would happen when the goroutine dies. Sounds bad.

**Comment by PieterD** [comment]
Thinking about it now, you're only getting stuff from Errors, so Events is still open.

I'd take a look at the code, but I won't see a computer until tonight.

**Comment by PieterD** [comment]
Oh. I got it. It's in your code. You create the watcher, defer close, and wait for stuff in a goroutine... But then you return from the function that has the defer close.

A question might be, is the events channel being properly closed by the goroutine?

**Comment by nathany** [comment]
@pbdeuchler It's this line right here:

```
defer watcher.Close()
```

Nothing in `Run()` is blocking. When it returns we close down the channels, and closed channels always receive the zero value (which is nil for interfaces like error).

You probably want to define a separate `func (dr *DiskRecieve) Stop() error` function to call Close later on in your program execution.

**Comment by nathany** [comment]
`event.Op&fsnotify.Write == fsnotify.Write` will never succeed when Events is returning a zero-value Event struct.

**Comment by nathany** [comment]
@PieterD I like how we both saw the issue at the exact same time. :smile:

**Comment by PieterD** [comment]
Hah! Sweet. I was in the train on my phone, so I had a few minutes.

By the wat, watcher.isClosed is racey in almost every case.

**Comment by PieterD** [comment]
Ah that's how the events chan wasn't reporting. Duh. Thanks :D

**Comment by pbdeuchler** [comment]
Oh man... Facepalming pretty hard over here. Thanks for the help guys!

**Comment by PieterD** [comment]
Happens to everyone. Good luck :)
