### ISSUE TITLE
Glob support

### ISSUE THREAD

**Issue by omeid** [go-fsnotify/fsnotify#70]
Hello,

Just a thought, I am using fsnotify for one of my projects and I have come across the issue of watching files that matches a specific glob.

Now I use [filepath.Glob and add the returned files to a watch a watch](https://github.com/slurp-contrib/watch/blob/master/watch.go#L15-L30), this works, but there is a problem, there is no convenient way to handle created files.

I am not sure about the complexity but being able to watch a pattern (for example, `frontend/*.js`) would be wicked.

**Comment by PieterD** [comment]
Yeah, it would :)

https://github.com/go-fsnotify/fsnotify/issues/10

**Comment by omeid** [comment]
Oh, I couldn't find anything with `glob`. Thanks. :)
